merge updates from NGWPC (#549)
* updated names and paths with new values

* corrected ngen-bmi variable names

* testing

* updated ngencerf start template v3

* updated ngencerf start template v3

* Handle permission/ownsership changes within SLURM job

* Fix path

* Write stdout to temporary location

* Move SLURM tmp files to their own directory

* Remove duplicate

* We need this line to change the permissions of the /ngecerf/data/run-logs  directory and potentially others

* Not use temporary files and directories. First change permissions of slurm script and output paths

* Not use temporary files and directories. First change permissions of slurm script and output paths

* Bring Miguel's changes back and add changes to fix ownership change timeout issue

* Update start-template-v3.sh

Revert this change
https://github.com/parallelworks/interactive_session/commit/080241b9b303ff613fe3c1a5b86980eb4637b82e
to fix:

```
Traceback (most recent call last):
  File "/ngen-app/nwm-cal-mgr/python/calibration.py", line 194, in <module>
    main(general, conf["model"])
  File "/ngen-app/nwm-cal-mgr/python/calibration.py", line 103, in main
    log_level_set()
  File "/ngen-app/nwm-cal-mgr/python/calibration.py", line 63, in log_level_set
    os.makedirs(log_file_dir, exist_ok=True)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/ngencerf/data/run-logs/ngen_cal_2025-09-23T14:45:39.152'
calibration.py exited with code 1
```

* small comment change to start template

* updated start-template

* updated start-template

* updated start template and slurm wrapper to chown and chmod only when necessary and in parallel

* updated start template and slurm wrapper to chown and chmod only when necessary and in parallel

* updated start template and slurm wrapper to chown and chmod only when necessary and in parallel

* updated start template to only check permissions on files and directories that have been modified since we last corrected permissions

* updated start template to only check permissions on files and directories that have been modified since we last corrected permissions

* updated start template file

* updated start template file

* updated start template file

* updated start template file

* updated start template file

* updated start template file

* updated start template and start yaml to default to not building ngencerf-server since we are now pulling it by default

* updated start template and start yaml to default to not building ngencerf-server since we are now pulling it by default

* updated start template and start yaml to default to not building ngencerf-server since we are now pulling it by default

* updated start template

* updated start template

* updated start template

* update start template to allow local build or pulling from registry for server

* comment changes in start template

* Remove submit-forecast-forcing-download-job endpoint

* Update submit-forecas-job endpoint

* Add submit-cold-start-job endpoint

* Fix typo

* Slurm script is written to output dir

* fix typo

* Fixed typo.

* Add /submit-verification-job endpoint

* adding read and write permissions for everyone

* Fix job-status endpoint when job is no longer running

* Add retries to callback

* No need to make these directories now

* Use central location for callback script and logs

* Rewrite callback logic to add retries at workflow restart

* Avoid rerunning callbacks for jobs that are still running and have no status

* Fix typo

* Start callback rerun before service

* Start callback rerun before service

* Rename script and exit if directory is missing

* Fix typo

* Resubmit also starting callbacks

* fix typo

* Fix directory path

* Increase max configuring time to 12 min

* Increase max configuring time

* Fix paths

* Exit if callback-inputs.sh is missing

* Fix typo

* Fix typo

* Fix typo

* Improve logs

* Add missing exit

* Increase nginx timeouts

---------

Co-authored-by: Miguel Pena <miguelp1986@gmail.com>
Co-authored-by: steve <steve@parallelworks.com>